USE backend_weatherloo;

INSERT INTO autonomy(autonomyId,name) VALUES (01,'Andalucía');
INSERT INTO autonomy(autonomyId,name) VALUES (02,'Aragón');
INSERT INTO autonomy(autonomyId,name) VALUES (03,'Principado de Asturias');
INSERT INTO autonomy(autonomyId,name) VALUES (04,'Illes Balears');
INSERT INTO autonomy(autonomyId,name) VALUES (05,'Canarias');
INSERT INTO autonomy(autonomyId,name) VALUES (06,'Cantabria');
INSERT INTO autonomy(autonomyId,name) VALUES (07,'Castilla y León');
INSERT INTO autonomy(autonomyId,name) VALUES (08,'Castilla-La Mancha');
INSERT INTO autonomy(autonomyId,name) VALUES (09,'Cataluña/Catalunya');
INSERT INTO autonomy(autonomyId,name) VALUES (10,'Comunitat Valenciana');
INSERT INTO autonomy(autonomyId,name) VALUES (11,'Extremadura');
INSERT INTO autonomy(autonomyId,name) VALUES (12,'Galicia');
INSERT INTO autonomy(autonomyId,name) VALUES (13,'Comunidad de Madrid');
INSERT INTO autonomy(autonomyId,name) VALUES (14,'Región de Murcia');
INSERT INTO autonomy(autonomyId,name) VALUES (15,'Comunidad Foral de Navarra');
INSERT INTO autonomy(autonomyId,name) VALUES (16,'País Vasco/Euskadi');
INSERT INTO autonomy(autonomyId,name) VALUES (17,'La Rioja');
INSERT INTO autonomy(autonomyId,name) VALUES (18,'Ciudad Autónoma de Ceuta');
INSERT INTO autonomy(autonomyId,name) VALUES (19,'Ciudad Autónoma de Melilla');

INSERT INTO province(id,name,autonomy_id,capital) VALUES (01,'Araba/Álava',16,'Vitoria-Gasteiz');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (02,'Albacete',08,'Albacete');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (03,'Alacant/Alicante',10,'Alicante/Alacant');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (04,'Almería',01,'Almería');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (05,'Ávila',07,'Ávila');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (06,'Badajoz',11,'Badajoz');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (07,'Illes Balears',04,'Palma de Mallorca');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (08,'Barcelona',09,'Barcelona');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (09,'Burgos',07,'Burgos');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (10,'Cáceres',11,'Cáceres');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (11,'Cádiz',01,'Cádiz');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (12,'Castelló/Castellón',10,'Castellón de la Plana/Castelló de la Plana');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (13,'Ciudad Real',08,'Ciudad Real');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (14,'Córdoba',01,'Córdoba');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (15,'A Coruña',12,'A Coruña');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (16,'Cuenca',08,'Cuenca');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (17,'Girona',09,'Girona');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (18,'Granada',01,'Granada');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (19,'Guadalajara',08,'Guadalajara');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (20,'Gipuzkoa',16,'Donostia/San Sebastián');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (21,'Huelva',01,'Huelva');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (22,'Huesca',02,'Huesca');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (23,'Jaén',01,'Jaén');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (24,'León',07,'León');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (25,'Lleida',09,'Lleida');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (26,'La Rioja',17,'Logroño');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (27,'Lugo',12,'Lugo');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (28,'Madrid',13,'Madrid');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (29,'Málaga',01,'Málaga');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (30,'Murcia',14,'Murcia');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (31,'Navarra',15,'Pamplona/Iruña');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (32,'Ourense',12,'Ourense');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (33,'Asturias',03,'Oviedo');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (34,'Palencia',07,'Palencia');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (35,'Las Palmas',05,'Las Palmas de Gran Canaria');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (36,'Pontevedra',12,'Pontevedra');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (37,'Salamanca',07,'Salamanca');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (38,'Santa Cruz de Tenerife',05,'Santa Cruz de Tenerife');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (39,'Cantabria',06,'Santander');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (40,'Segovia',07,'Segovia');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (41,'Sevilla',01,'Sevilla');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (42,'Soria',07,'Soria');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (43,'Tarragona',09,'Tarragona');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (44,'Teruel',02,'Teruel');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (45,'Toledo',08,'Toledo');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (46,'València/Valencia',10,'Valencia');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (47,'Valladolid',07,'Valladolid');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (48,'Bizkaia',16,'Bilbao');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (49,'Zamora',07,'Zamora');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (50,'Zaragoza',02,'Zaragoza');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (51,'Ceuta',18,'Ceuta');
INSERT INTO province(id,name,autonomy_id,capital) VALUES (52,'Melilla',19,'Melilla');


